version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ontime
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - '8050:8050'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ontime
    depends_on:
      - db

volumes:
  pgdata:
